name: Trivy Scan for Frontend and Backend

on:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # --- Frontend ---
      - name: Build frontend image
        run: docker build -t docker.io/my-organization/frontend:${{ github.sha }} ./frontend

      - name: Run Trivy vulnerability scanner on frontend
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/my-organization/frontend:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-frontend.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'

      - name: Upload frontend scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-frontend.sarif'
          category: trivy-frontend 

      # --- Backend ---
      - name: Build backend image
        run: docker build -t docker.io/my-organization/backend:${{ github.sha }} ./backend

      - name: Run Trivy vulnerability scanner on backend
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/my-organization/backend:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-backend.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'

      - name: Upload backend scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-backend.sarif'
          category: trivy-backend
